#!/bin/bash

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# If no files, skip scan
# no idea how this could happen, but thought better to have it
if [ -z "$STAGED_FILES" ]; then
    printf "No files to scan for secrets."
    exit 0
fi


# Compile the java file
javac scanner/*.java
if [ $? -ne 0 ]; then
    echo "Scanner compilation failed. Aborting commit."
    exit 1
fi

# Create temp directory and copy staged files into it
TMPDIR=$(mktemp -d)
for file in $STAGED_FILES; do
    mkdir -p "$TMPDIR/$(dirname "$file")"
    git show ":$file" > "$TMPDIR/$file"
done

# Run the scanner
java scanner.SecretScanner "$TMPDIR"

# Echo result back to the Git hook
SCAN_RESULT=$?

# Clean up
rm -rf "$TMPDIR"

# Go back to repo root
cd ..

# Check result
if [ "$SCAN_RESULT" -ne 0 ]; then
    printf "Secret scan failed. Commit blocked.\n\n"
    exit 1
fi

printf "No secrets found. Proceeding with commit.\n\n"
exit 0
